- name: download epel
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noar    ch.rpm"
    dest: "/tmp/epel-release-latest-7.noarch.rpm"

- name: install epel
  yum:
    name: "/tmp/epel-release-latest-7.noarch.rpm"
    state: present

- name: install basic packages
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - python34
    - nginx
    - git

- name: copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: copy gse service
  copy:
    src: gse.service
    dest: /usr/lib/systemd/system/gse.service

- name: create nginx user
  user:
    name: nginx
    shell: /bin/bash
    createhome: yes
    home: /home/nginx

- name: give users sudo
  template:
    src: ansible-users.j2
    dest: /etc/sudoers.d/ansible-users

- name: install gse software
  git:
    repo: "https://github.com/msmitty12/gse.git"
    accept_hostkey: yes
    dest: /home/nginx/gse

- name: copy wsgi.py
  copy:
    src: wsgi.py
    dest: /home/nginx/gse/main/gse/wsgi.py
